spring:
  application:
    name: health-first-server
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:health_first_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    
  # Liquibase Configuration - Temporarily disabled for H2 development
  liquibase:
    enabled: false
    
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-specific-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    jwtExpirationMs: 86400000 # 24 hours
    jwtRefreshExpirationMs: 604800000 # 7 days
  base-url: http://localhost:8080

# Logging Configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com.healthfirst: DEBUG
    com.twilio: INFO  # Enable Twilio debug logging if needed
    
# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration: 86400000 # 24 hours
    refreshExpiration: 604800000 # 7 days
